[package]
name = "p2pcv-server"
version = "0.1.2-snapshot"
edition = "2021"
license = "AGPL-3.0-or-later"
repository = "https://github.com/Relacibo/p2pcv-server"

[[bin]]
name = "app"
path = "src/main.rs"

[workspace]
members = ["libs/pvpcv_bebop", "tools/p2p_dbg", "migration"]

[dependencies]
axum = { version = "0.8", features = ["macros"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["cors", "trace"] }
axum-extra = { version = "0.10", features = ["typed-header"] }
sea-orm = { version = "1.1", features = ["sqlx-postgres", "runtime-tokio-native-tls", "macros", "with-uuid", "with-chrono"] }
sea-orm-migration = { version = "1.1", features = ["sqlx-postgres", "runtime-tokio-native-tls"] }
env_logger = "^0.11.5"
serde = { version = "^1.0.210", features = ["derive"] }
serde_derive = "1.0.210"
serde_json = "1.0.128"
uuid = { version = "1.2", features = ["serde", "v4"] }
chrono = { version = "0.4.38", features = ["serde"] }
jsonwebtoken = "9.3.0"
reqwest = { version = "0.12.7", features = ["json"] }
dotenvy = "0.15.7"
base64 = "0.22"
tokio = { version = "1.40.0", features = ["full"] }
thiserror = "1.0.63"
serde_with = { version = "3.9.0", features = ["chrono", "base64"] }
log = "0.4.19"
async-trait = "0.1.82"
validator = { version = "0.18", features = ["derive"] }
rand = "0.8.5"
futures = "0.3.30"
dashmap = "6.1.0"
p2pcv-bebop = { path = "libs/pvpcv_bebop" }
migration = { path = "migration" }
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", features = [
  "ed25519",
  "gossipsub",
  "macros",
  "tokio",
  "ping",
  "request-response",
], rev = "a2a281609a0a64b211f7917aa856924983b63200" }
libp2p-webrtc = { git = "https://github.com/libp2p/rust-libp2p.git", features = [
  "tokio",
  "pem",
], rev = "a2a281609a0a64b211f7917aa856924983b63200" }
libp2p-core = { git = "https://github.com/libp2p/rust-libp2p.git", rev = "a2a281609a0a64b211f7917aa856924983b63200" }
