[package]
name = "p2pcv-server"
version = "0.1.1-snapshot"
edition = "2021"
license = "AGPLV3"
repository = "https://github.com/Relacibo/p2pcv-server"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.1.0"
env_logger = "0.9"
diesel = { version = "1.4", features = [
  "postgres",
  "uuidv07",
  "chrono",
  "r2d2",
] }
r2d2 = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
macro-attr = "0.2"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "8.1"
reqwest = "0.11"
reqwest-middleware = "0.1.6"
dotenv = "0.15"
base64 = "0.13"
tokio = { version = "1.17", features = ["sync"] }
futures = "0.3.21"
actix-web-httpauth = "0.6.0"

[build-dependencies]
static-files = "0.2.1"
