[package]
name = "p2pcv-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-rc.1"
env_logger = "0.9.0"
diesel = { version = "1.4.8", features = ["postgres", "uuidv07", "chrono"] }
r2d2-diesel = "1.0.0"
r2d2 = "0.8.9"
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.78"
macro-attr = "0.2.0"
uuid = { version = "0.8.2", features = ["serde"] }
chrono = { version = "0.4.19", features = ["serde"] }
