[package]
name = "p2pcv-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0"
env_logger = "0.9"
diesel = { version = "1.4", features = ["postgres", "uuidv07", "chrono"] }
r2d2-diesel = "1.0"
r2d2 = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
macro-attr = "0.2"
uuid = { version = "0.8", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "8.1"
reqwest = "0.11"
reqwest-middleware = "0.1.6"
dotenv = "0.15"
base64 = "0.13"
tokio = { version = "1.17", features = ["sync"] }
http-cache-reqwest = { version = "0.4.3", default-features = false, features = [
  "manager-moka",
] }

[build-dependencies]
static-files = "0.2.1"
