//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2
//!
//! NOTE: `auth_providers` was added manually for this refactor.
//! Run `just entities` after applying the migration to regenerate this module.

pub mod prelude;

pub mod auth_providers;
pub mod friend_requests;
pub mod friends;
pub mod lichess_access_tokens;
pub mod refresh_tokens;
pub mod users;
