//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub use super::auth_providers::Entity as AuthProviders;
pub use super::friend_requests::Entity as FriendRequests;
pub use super::friends::Entity as Friends;
pub use super::lobbies::Entity as Lobbies;
pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::users::Entity as Users;
