//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

pub use super::friend_requests::Entity as FriendRequests;
pub use super::friends::Entity as Friends;
pub use super::google_users::Entity as GoogleUsers;
pub use super::lichess_access_tokens::Entity as LichessAccessTokens;
pub use super::lichess_users::Entity as LichessUsers;
pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::users::Entity as Users;
