//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub user_name: String,
    pub display_name: String,
    #[sea_orm(unique)]
    pub email: String,
    pub locale: String,
    pub verified_email: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::google_users::Entity")]
    GoogleUsers,
    #[sea_orm(has_one = "super::lichess_users::Entity")]
    LichessUsers,
    #[sea_orm(has_many = "super::refresh_tokens::Entity")]
    RefreshTokens,
}

impl Related<super::google_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GoogleUsers.def()
    }
}

impl Related<super::lichess_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LichessUsers.def()
    }
}

impl Related<super::refresh_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefreshTokens.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
